version: '3'

services:
  cron:
    build: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env.docker
  mongo:
    image: mongo:3.7
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume: